name: study_tool_fr1
description: "A vocabulary learning tool using a graph visualization, built to study language with my friends."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  google_fonts: ^6.3.1
  go_router: ^16.2.1
  graphview: ^1.2.0
  firebase_ai: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
