// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4opiKffJ4qe4f5NAir-LT95NeivX3jw',
    appId: '1:969673828986:web:50b6fea10c35c2f3ac29c3',
    messagingSenderId: '969673828986',
    projectId: 'study-tool-fr1',
    authDomain: 'study-tool-fr1.firebaseapp.com',
    storageBucket: 'study-tool-fr1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpszFFcUkfpVi2PfYwcX8__AOjmh0dbhI',
    appId: '1:969673828986:android:d73f06dc83be2918ac29c3',
    messagingSenderId: '969673828986',
    projectId: 'study-tool-fr1',
    storageBucket: 'study-tool-fr1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm3FdT9SwlkexUxZnCzVRFUZ0QEbi-4h8',
    appId: '1:969673828986:ios:db1a2cb6e3c68ea2ac29c3',
    messagingSenderId: '969673828986',
    projectId: 'study-tool-fr1',
    storageBucket: 'study-tool-fr1.firebasestorage.app',
    iosBundleId: 'com.example.studyToolFr1',
  );

}